# 核心组件部署
# 基础组件  网关和uaa

version: "3.2"
services:
  # 1、网关zuul
  zuul-server:
    # 镜像地址
    image: 192.168.2.226:5000/zuul-server:0.0.1-SNAPSHOT
    # 容器名称
    container_name: zuul-server
    ports:
      # 端口映射
      - "8765:8765"
    env_file:
      # 加载环境变量
      - ./service.env
    networks:
      # 加入集群网络
      - swarm_net
    volumes:
      # 将宿主机上的文件挂载到容器内
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      # 实例数量
      replicas: 1
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '0.5'
          # 内存限制
          memory: 512M
    # 健康检查，启动后，当这个命令执行没问题，才会任何这个服务启动成功
    healthcheck:
      # 命令
      test: ["CMD", "curl", "-f", "http://localhost:8765/info"]
      # 间隔时间，安装应用的预计启动时间来设置。比如我们这个springcloud的应用，一般在1分钟半内预计启动完成
      interval: 1m30s
      timeout: 10s
      # 重试次数
      retries: 5
  # 2、UAA
  uaa-interface:
    # 镜像地址
    image: 192.168.2.226:5000/uaa-interface:0.0.1-SNAPSHOT
    # 容器名称
    container_name: uaa-interface
    ports:
      # 端口映射
      - "9004:9004"
    env_file:
      # 加载环境变量
      - ./service.env
    networks:
      # 加入集群网络
      - swarm_net
    volumes:
      # 将宿主机上的文件挂载到容器内
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      # 实例数量
      replicas: 1
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '0.5'
          # 内存限制
          memory: 512M
    # 健康检查，启动后，当这个命令执行没问题，才会任何这个服务启动成功
    healthcheck:
      # 命令
      test: ["CMD", "curl", "-f", "http://localhost:9004/info"]
      # 间隔时间，安装应用的预计启动时间来设置。比如我们这个springcloud的应用，一般在1分钟半内预计启动完成
      interval: 1m30s
      timeout: 10s
      # 重试次数
      retries: 5
networks:
  swarm_net:
    external: true
  